- name: conditions in ansible
  hosts: local
  connection: local

  vars:
    NUMBER: 70

  tasks: 
    - name: print if number is less then or equal to 100
      ansible.builtin.debug:
        msg: "the given nynmber is {{ NUMBER }}, less then or equal to 100"
      when: NUMBER <= 100
    
    - name: print if number is greater then  100
      ansible.builtin.debug:
        msg: "the given nynmber is {{ NUMBER }}, greater then 100"
      when: NUMBER > 100
    