- name: instaling the packges
  hosts: frontend
  become: yes
  tasks: 
  - name: install packges
    ansible.builtin.packge:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - nginx
    - zip