- name: installing nginx and run
  hosts: webserver
  connection: webserver
  become: yes
  tasks: 
    - name: install inginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: nginx start 
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
